-----------------------CREATE DATABASE QLHS
CREATE DATABASE QLHS
GO
USE QLHS
GO
-----------------TABLE
-- HOCSINH 
-- QUATRINHHOC
-- LOP
-- KHOI
-- HOCKY
-- CHUONGTRINHHOC
-- BANGDIEMMON
-- CT_BANGDIEMMON
-- LOAIHINHKIEMTRA
-- TONGKETHOCKY
-- MONHOC
-- TONGKETMON

CREATE TABLE HOCSINH
(
	MAHS INT IDENTITY(1000,1) PRIMARY KEY,
	HO NVARCHAR(40) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	GIOITINH NVARCHAR(20) NOT NULL,
	NGSINH DATE,
	DIACHI NVARCHAR(200),
	EMAIL NVARCHAR(100),
)

CREATE TABLE MONHOC
(
	MAMH INT IDENTITY(1000,1) PRIMARY KEY,
	TENMH NVARCHAR(100) NOT NULL,
	DIEMDAT FLOAT DEFAULT 5,
)

CREATE TABLE HOCKY
(
	MAHK INT IDENTITY(1000,1) PRIMARY KEY,
	TENHOCKY NVARCHAR(100) NOT NULL,
	NAMHOC INT,
)

CREATE TABLE KHOI
(
	MAKHOI INT IDENTITY(1000,1) PRIMARY KEY,
	TENKHOI NVARCHAR(100) NOT NULL,
)

CREATE TABLE LOP
(
	MALOP INT IDENTITY(1000,1) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	SISO INT,
	--MAHK INT FOREIGN KEY REFERENCES HOCKY(MAHK),
	MAKHOI INT FOREIGN KEY REFERENCES KHOI(MAKHOI),
)

CREATE TABLE QUATRINHHOC
(
	MAQTH INT IDENTITY(1000,1) PRIMARY KEY,
	MALOP INT FOREIGN KEY REFERENCES LOP(MALOP),
	MAHS INT FOREIGN KEY REFERENCES HOCSINH(MAHS),
	MAHK INT FOREIGN KEY REFERENCES HOCKY(MAHK),
	DIEMTB_HOCKY FLOAT,
)

CREATE TABLE CHUONGTRINHHOC
(
	MACTH INT IDENTITY(1000, 1)PRIMARY KEY,
	MAKHOI INT FOREIGN KEY REFERENCES KHOI(MAKHOI),
	MAMH INT FOREIGN KEY REFERENCES MONHOC(MAMH),
	HESO FLOAT,
)

CREATE TABLE BANGDIEMMON
(
	MABDM INT IDENTITY(1000,1) PRIMARY KEY,
	MAMH INT FOREIGN KEY REFERENCES MONHOC(MAMH),
	MAQTH INT FOREIGN KEY REFERENCES QUATRINHHOC(MAQTH),
	DIEMTRUNGBINHMON FLOAT,
)
CREATE TABLE TONGKETHOCKY
(
	MALOP INT FOREIGN KEY REFERENCES LOP(MALOP),
	MAHK INT FOREIGN KEY REFERENCES HOCKY(MAHK),
	SOLUONGDAT INT,
	TILE FLOAT,
	SISO INT,
	PRIMARY KEY (MALOP, MAHK),
)

CREATE TABLE LOAIHINHKIEMTRA
(
	MALHKT INT IDENTITY(1000,1) PRIMARY KEY,
	TENLHKT NVARCHAR(200),
	HESODIEM FLOAT,
	THOIGIANKIEMTRA INT,
)


CREATE TABLE CT_BANGDIEMMON
(
	MACT_BDM INT IDENTITY(1000,1) PRIMARY KEY,
	MALHKT INT FOREIGN KEY REFERENCES LOAIHINHKIEMTRA(MALHKT),
	MABDM INT FOREIGN KEY REFERENCES BANGDIEMMON(MABDM),
	DIEM FLOAT,
	-- PRIMARY KEY (MALHKT, MABDM),
)

CREATE TABLE TONGKETMON
(
	MATKM INT IDENTITY(1000,1) PRIMARY KEY,
	MAMH INT FOREIGN KEY REFERENCES MONHOC(MAMH),
	MALOP INT FOREIGN KEY REFERENCES LOP(MALOP),
	MAHK INT FOREIGN KEY REFERENCES HOCKY(MAHK),
	SOLUONGDAT INT,
	TILE FLOAT,
	SISO INT,
)

CREATE TABLE THAMSO
(
	MATHAMSO INT IDENTITY(1000,1) PRIMARY KEY,
	TENTHAMSO NVARCHAR(100),
	GIATRI FLOAT,
)
