USE QLHS
GO
-- Tuổi học sinh từ 15 tới 20
CREATE TRIGGER TRG_INS_HS_AGE ON HOCSINH
FOR INSERT,UPDATE
AS
BEGIN
	IF NOT EXISTS(SELECT *
		FROM INSERTED
		WHERE (YEAR(GETDATE()) - YEAR(NGSINH) >= (SELECT GIATRI FROM THAMSO WHERE TENTHAMSO = 'TuoiToiThieu')
			AND YEAR(GETDATE()) - YEAR(NGSINH) <= (SELECT GIATRI FROM THAMSO WHERE TENTHAMSO = 'TuoiToiDa')))
	BEGIN
		RAISERROR('TUOI KHONG HOP LE',16,1)
		ROLLBACK TRANSACTION
	END
END
GO
CREATE TRIGGER TRG_INS_HK ON HOCKY
FOR INSERT
AS
BEGIN
	UPDATE HOCKY SET TENHOCKY = CONCAT(TENHOCKY, N' Năm ', NAMHOC)
END
GO
---------------------------------------------------------------------------- THEM ON DELETE CASCADE
ALTER TABLE QUATRINHHOC ADD CONSTRAINT fk_mahs_qth FOREIGN KEY (MAHS) REFERENCES HOCSINH(MAHS) ON DELETE CASCADE
ALTER TABLE BANGDIEMMON ADD CONSTRAINT fk_maqth_bdm FOREIGN KEY (MAQTH) REFERENCES QUATRINHHOC(MAQTH) ON DELETE CASCADE
ALTER TABLE CT_BANGDIEMMON ADD CONSTRAINT fk_mabdm_ctbdm FOREIGN KEY (MABDM) REFERENCES BANGDIEMMON(MABDM) ON DELETE CASCADE
ALTER TABLE CHUONGTRINHHOC ADD CONSTRAINT fk_mamh_cth FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH) ON DELETE CASCADE
ALTER TABLE BANGDIEMMON ADD CONSTRAINT fk_mamh_bdm FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH) ON DELETE CASCADE
ALTER TABLE TONGKETMON ADD CONSTRAINT fk_mamh_tkm FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH) ON DELETE CASCADE
ALTER TABLE QUATRINHHOC ADD CONSTRAINT fk_malop_qth FOREIGN KEY (MALOP) REFERENCES LOP(MALOP) ON DELETE CASCADE
ALTER TABLE TONGKETMON ADD CONSTRAINT fk_mahs_tkm FOREIGN KEY (MALOP) REFERENCES LOP(MALOP) ON DELETE CASCADE
ALTER TABLE TONGKETHOCKY ADD CONSTRAINT fk_mahs_tkhk FOREIGN KEY (MALOP) REFERENCES LOP(MALOP) ON DELETE CASCADE
-----------------------------------------------------------------------KIEM TRA TEN TRUNG
CREATE UNIQUE NONCLUSTERED INDEX [UIX_TENMH]
    ON MONHOC
    ( [TENMH] ASC)
GO
CREATE UNIQUE NONCLUSTERED INDEX [UIX_TENLOP]
    ON LOP
    ( [TENLOP] ASC) 
GO
CREATE UNIQUE NONCLUSTERED INDEX [UIX_MAMON_MAKHOI]
    ON CHUONGTRINHHOC
    ( [MAMH],[MAKHOI] ASC )
GO
CREATE UNIQUE NONCLUSTERED INDEX [UIX_MAMON_MALOP_MAHK]
    ON TONGKETMON
    ( [MAMH],[MALOP],[MAHK] ASC )
GO
CREATE UNIQUE NONCLUSTERED INDEX [UIX_MALOP_MAHK]
    ON TONGKETHOCKY
    ( [MALOP],[MAHK] ASC )
GO
