USE QLHS
GO
----------------------------- LOP------------------------------------TINH SI SO MOI LOP
UPDATE LOP
SET SISO = (SELECT COUNT(QTH.MAQTH) FROM QUATRINHHOC QTH WHERE LOP.MALOP = QTH.MALOP)
GO
----------------------------- HOCKY------------------------------------TAO TEN HOC KY
ALTER TABLE HOCKY ADD HOCKY NVARCHAR(40)
GO
UPDATE HOCKY SET HOCKY = CONCAT(TENHOCKY, N' Năm ', NAMHOC)
GO

----------------------------- QUATRINHHOC------------------------------------TINH DIEM TRUNG BINH HOC KY
UPDATE QUATRINHHOC
SET DIEMTB_HOCKY = (SELECT SUM(BDM.DIEMTRUNGBINHMON*CTH.HESO)/SUM(CTH.HESO) FROM BANGDIEMMON BDM, CHUONGTRINHHOC CTH , LOP L
WHERE QUATRINHHOC.MAQTH = BDM.MAQTH
AND QUATRINHHOC.MALOP = L.MALOP
AND L.MAKHOI = CTH.MAKHOI
AND BDM.MAMH = CTH.MAMH)
GO
----------------------------- BANGDIEMMON------------------------------------TINH DIEM TRUNG BINH MON
UPDATE BANGDIEMMON
SET DIEMTRUNGBINHMON = (SELECT SUM(CTBDM.DIEM*LHKT.HESODIEM) FROM CT_BANGDIEMMON CTBDM INNER JOIN LOAIHINHKIEMTRA LHKT ON CTBDM.MALHKT = LHKT.MALHKT WHERE CTBDM.MABDM = BANGDIEMMON.MABDM)
/(SELECT SUM(LHKT.HESODIEM) FROM CT_BANGDIEMMON CTBDM INNER JOIN LOAIHINHKIEMTRA LHKT ON CTBDM.MALHKT = LHKT.MALHKT
WHERE CTBDM.MABDM = BANGDIEMMON.MABDM)
GO
----------------------------- TONGKETHOCKY------------------------------------TINH SO LUONG DAT, TI LE DAT
UPDATE TONGKETHOCKY
SET SOLUONGDAT = (SELECT COUNT(QTH.MAQTH) FROM QUATRINHHOC QTH, THAMSO TS
WHERE QTH.MALOP = TONGKETHOCKY.MALOP AND QTH.DIEMTB_HOCKY > TS.GIATRI AND TS.TENTHAMSO='DiemDatHocKy')
GO
UPDATE TONGKETHOCKY
SET SISO = (SELECT SISO FROM LOP WHERE TONGKETHOCKY.MALOP = LOP.MALOP)
GO
UPDATE TONGKETHOCKY
SET TILE = SOLUONGDAT / SISO
GO

----------------------------- TONGKETMON------------------------------------TINH SO LUONG DAT, TI LE DAT
/*
UPDATE TONGKETMON
SET SOLUONGDAT = 
(SELECT DISTINCT COUNT(BDM.MABDM) FROM BANGDIEMMON BDM INNER JOIN QUATRINHHOC QTH ON BDM.MAQTH = QTH.MAQTH
WHERE TONGKETMON.MAMH = BDM.MAMH AND TONGKETMON.MAHK = QTH.MAHK AND TONGKETMON.MALOP = QTH.MALOP AND BDM.DIEMTRUNGBINHMON > 5)
GO
*/
UPDATE TONGKETMON
SET SOLUONGDAT = 
(SELECT DISTINCT COUNT(BDM.MABDM) FROM BANGDIEMMON BDM INNER JOIN QUATRINHHOC QTH ON BDM.MAQTH = QTH.MAQTH, MONHOC MH
WHERE TONGKETMON.MAMH = BDM.MAMH AND TONGKETMON.MAHK = QTH.MAHK AND TONGKETMON.MALOP = QTH.MALOP AND BDM.DIEMTRUNGBINHMON > MH.DIEMDAT AND MH.MAMH = BDM.MAMH)
GO
UPDATE TONGKETMON
SET SISO = (SELECT SISO FROM LOP WHERE TONGKETMON.MALOP = LOP.MALOP)
GO
UPDATE TONGKETMON
SET TILE = SOLUONGDAT / SISO
GO

/*
SELECT SUM(BDM.DIEMTRUNGBINHMON*CTH.HESO) FROM BANGDIEMMON BDM, CHUONGTRINHHOC CTH , LOP L, QUATRINHHOC
WHERE QUATRINHHOC.MAQTH = BDM.MAQTH AND QUATRINHHOC.MALOP = L.MALOP AND L.MAKHOI = CTH.MAKHOI AND BDM.MAMH = CTH.MAMH
AND BDM.MAQTH = 1000
SELECT SUM(CTH.HESO) FROM BANGDIEMMON BDM, CHUONGTRINHHOC CTH , LOP L, QUATRINHHOC
WHERE QUATRINHHOC.MAQTH = BDM.MAQTH AND QUATRINHHOC.MALOP = L.MALOP AND L.MAKHOI = CTH.MAKHOI AND BDM.MAMH = CTH.MAMH
AND BDM.MAQTH = 1000
UPDATE CHUONGTRINHHOC
SET HESO = 1 WHERE MAKHOI = 1000 AND MAMH = 1000
UPDATE CHUONGTRINHHOC
SET HESO = 3 WHERE MAKHOI = 1000 AND MAMH = 1002
update BANGDIEMMON
SET DIEMTRUNGBINHMON = 7 WHERE MAQTH = 1000 AND BANGDIEMMON.MAMH = 1000
*/
