USE QLHS
GO
---------------------------------------------------------------------------- TIEP NHAN HOC SINH
CREATE PROCEDURE THEMHOCSINH
	@MAHS INT,
	@HO NVARCHAR(40),
	@TEN NVARCHAR(10),
	@GIOITINH NVARCHAR(20),
	@NGSINH DATE,
	@DIACHI NVARCHAR(200),
	@EMAIL NVARCHAR(100)
AS
BEGIN
	INSERT INTO HOCSINH(MAHS, HO, TEN, GIOITINH, NGSINH, DIACHI, EMAIL)
	VALUES (@MAHS, @HO, @TEN, @GIOITINH, @NGSINH, @DIACHI, @EMAIL)
END
GO
---------------------------------------------------------------------------- LAP DANH SACH LOP
CREATE PROCEDURE THEMLOP
	@MALOP	INT,
	@TENLOP NVARCHAR(100),
	@SISO INT,
	@MAKHOI INT
AS
BEGIN
	INSERT INTO LOP(MALOP, TENLOP, SISO, MAKHOI)
	VALUES (@MALOP, @TENLOP, @SISO, @MAKHOI)
END
GO
---------------------------------------------------------------------------- THEM HOC SINH VAO LOP
CREATE PROCEDURE THEMHOCSINHVAOLOP
	@MALOP INT,
	@MAHS INT
AS
BEGIN
	INSERT INTO QUATRINHHOC(MALOP, MAHS)
	VALUES (@MALOP, @MAHS)
	UPDATE LOP
	SET SISO = (SELECT COUNT(QTH.MAQTH) FROM QUATRINHHOC QTH WHERE LOP.MALOP = QTH.MALOP)
	WHERE MALOP = @MALOP
END
GO
---------------------------------------------------------------------------- XOA HOC SINH KHOI LOP
CREATE PROCEDURE XOAHOCSINHKHOILOP
	@MALOP INT,
	@MAHS INT
AS
BEGIN
	DELETE FROM QUATRINHHOC
	WHERE MALOP = @MALOP AND MAHS = @MAHS
	UPDATE LOP
	SET SISO = (SELECT COUNT(QTH.MAQTH) FROM QUATRINHHOC QTH WHERE LOP.MALOP = QTH.MALOP)
	WHERE MALOP = @MALOP
END
GO
---------------------------------------------------------------------------- TRA CUU HOC SINH
CREATE PROCEDURE TRACUUHOCSINH
	@HO NVARCHAR(40),
	@TEN NVARCHAR(10)
AS
BEGIN
	SELECT MAHS, HO, TEN, GIOITINH, NGSINH FROM HOCSINH WHERE HO LIKE '%@HO%' OR TEN LIKE '%@TEN%Q'
END
GO
---------------------------------------------------------------------------- THAY DOI TUOI TOI THIEU, TUOI TOI DA
CREATE PROCEDURE THAYDOITUOI
	@TuoiToiThieu INT,
	@TuoiToiDa INT
AS
	BEGIN 
		UPDATE THAMSO SET GIATRI = @TuoiToiThieu WHERE TENTHAMSO = 'TuoiToiThieu'
		UPDATE THAMSO SET GIATRI = @TuoiToiDa WHERE TENTHAMSO = 'TuoiToiDa'
	END
GO
---------------------------------------------------------------------------- THAY DOI SI SO TOI DA CUA CAC LOP
CREATE PROCEDURE THAYDOISISO
	@SISO INT
AS
	BEGIN
		UPDATE THAMSO SET GIATRI = @SISO WHERE TENTHAMSO = 'SiSoToiDa'
	END
GO
---------------------------------------------------------------------------- SUA DIEM DAT CHO MON HOC
/*
CREATE PROCEDURE SUADIEMDATMONHOC
	@MAMH INT,
	@TENTHAMSO NVARCHAR(100),
	@DIEM FLOAT
AS
	BEGIN
		UPDATE THAMSO SET GIATRI = @DIEM WHERE TENTHAMSO = @TENTHAMSO
		UPDATE TONGKETMON SET SOLUONGDAT = 
				(SELECT DISTINCT COUNT(BDM.MABDM) FROM BANGDIEMMON BDM INNER JOIN QUATRINHHOC QTH ON BDM.MAQTH = QTH.MAQTH, THAMSO TS
				WHERE TONGKETMON.MAMH = BDM.MAMH
					AND TONGKETMON.MAHK = QTH.MAHK
					AND TONGKETMON.MALOP = QTH.MALOP
					AND BDM.DIEMTRUNGBINHMON > TS.GIATRI
					AND TS.TENTHAMSO = @TENTHAMSO)
	END
GO
*/
CREATE PROCEDURE SUADIEMDATMONHOC
	@MAMH INT,
	@DIEMDAT FLOAT
AS
	BEGIN
		UPDATE MONHOC
		SET DIEMDAT = @DIEMDAT
		WHERE MAMH = @MAMH
		UPDATE TONGKETMON
		SET SOLUONGDAT = 
		(SELECT DISTINCT COUNT(BDM.MABDM) FROM BANGDIEMMON BDM INNER JOIN QUATRINHHOC QTH ON BDM.MAQTH = QTH.MAQTH, MONHOC MH
		WHERE TONGKETMON.MAMH = BDM.MAMH AND TONGKETMON.MAHK = QTH.MAHK AND TONGKETMON.MALOP = QTH.MALOP AND BDM.DIEMTRUNGBINHMON > MH.DIEMDAT AND MH.MAMH = BDM.MAMH)
		WHERE TONGKETMON.MAMH = @MAMH
	END
GO
---------------------------------------------------------------------------- XEM DANH SACH LOP
CREATE PROCEDURE XEMDANHSACHLOP
	@TENLOP NVARCHAR(100),
	@HOCKY NVARCHAR(40)
AS
	BEGIN
		SELECT HS.HO, HS.TEN, HS.GIOITINH, HS.NGSINH, HS.DIACHI FROM HOCSINH HS, QUATRINHHOC QTH, LOP L, HOCKY HK
		WHERE HS.MAHS = QTH.MAHS
		AND QTH.MALOP = L.MALOP
		AND QTH.MAHK = HK.MAHK
		AND L.TENLOP = @TENLOP
		AND HK.TENHOCKY = @HOCKY
	END
GO
/*
EXEC XEMDANHSACHLOP
	@TENLOP = '11A1',
	@HOCKY = N'Học kỳ 2 Năm 2020'
*/
----------------------------------------------------------------------------- TAO BAO CAO TONG KET MON
CREATE PROCEDURE THEMBAOCAOTONGKETMON
	@MAMH INT,
	@MAHK INT
AS
	BEGIN
		insert into TONGKETMON(MALOP,MAMH,MAHK,SOLUONGDAT,TILE) 
		select R1.MALOP, R1.MAMH, R1.MAHK, R1.SLDAT, CAST(ROUND(R1.SLDAT*100.0/R2.SISO,2) as numeric(5,2)) as TLDAT
		from 
			(select L.MALOP, L.TENLOP, HK.MAHK, MH.MAMH, count(*) as SLDAT
			from QUATRINHHOC QT join LOP L on QT.MALOP = L.MALOP join HOCKY HK on QT.MAHK = HK.MAHK join BANGDIEMMON BD on BD.MAQTH = QT.MAQTH join MONHOC MH on BD.MAMH = MH.MAMH
			where MH.MAMH = @MAMH and HK.MAHK = @MAHK and DIEMTRUNGBINHMON >= DIEMDAT
			group by L.MALOP, L.TENLOP, HK.MAHK, MH.MAMH) as R1 join
			(select L.MALOP, HK.MAHK, MH.MAMH, count(*) as SISO
			from QUATRINHHOC QT join LOP L on QT.MALOP = L.MALOP join HOCKY HK on QT.MAHK = HK.MAHK join BANGDIEMMON BD on BD.MAQTH = QT.MAQTH join MONHOC MH on BD.MAMH = MH.MAMH
			where MH.MAMH = @MAMH and HK.MAHK = @MAHK 
			group by L.MALOP, HK.MAHK, MH.MAMH) as R2 on R1.MALOP = R2.MALOP and R1.MAHK = R2.MAHK and R1.MAMH = R2.MAMH
	END
GO
----------------------------------------------------------------------------- TAO BAO CAO TONG KET HOC KY
CREATE PROCEDURE THEMBAOCAOTONGKETHOCKY
	@MAHK INT
AS
	BEGIN
		insert into TONGKETHOCKY(MALOP,MAHK,SISO,SOLUONGDAT,TILE) 
		select R1.MALOP, R1.MAHK, R2.SISO,R1.SLDAT, CAST(ROUND(R1.SLDAT*100.0/R2.SISO,2) as numeric(5,2)) as TLDAT
		from 
			(select L.MALOP,L.TENLOP, HK.MAHK, count(*) as SLDAT
			from QUATRINHHOC QT join LOP L on QT.MALOP = L.MALOP join HOCKY HK on QT.MAHK = HK.MAHK, THAMSO TS 
			where HK.MAHK = @MAHK and DIEMTB_HOCKY >= TS.GIATRI and TS.TENTHAMSO = 'DiemDatHocKy'
			group by L.MALOP,L.TENLOP, HK.MAHK) as R1 join
			(select L.MALOP, HK.MAHK, count(*) as SISO
			from QUATRINHHOC QT join LOP L on QT.MALOP = L.MALOP join HOCKY HK on QT.MAHK = HK.MAHK
			where HK.MAHK = @MAHK
			group by L.MALOP, HK.MAHK) as R2 on R1.MALOP = R2.MALOP and R1.MAHK = R2.MAHK
	END
GO
